// <auto-generated />
using System;
using System.Text.Json;
using IsoGuard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IsoGuard.Api.Migrations
{
    [DbContext(typeof(IsoGuardDbContext))]
    [Migration("20260727090448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IsoGuard.Api.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("account_number");

                    b.Property<decimal>("Balance")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_account_number");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_accounts_created_by_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_accounts_owner_id");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_balance_nonnegative", "balance >= 0");

                            t.HasCheckConstraint("ck_accounts_status", "status IN ('ACTIVE', 'BLOCKED', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.AnomalyResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspicious");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_version");

                    b.Property<double>("NormalizedAnomalyScore")
                        .HasColumnType("double precision")
                        .HasColumnName("normalized_anomaly_score");

                    b.Property<double>("RawModelScore")
                        .HasColumnType("double precision")
                        .HasColumnName("raw_model_score");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_anomaly_results");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_anomaly_results_transaction_id");

                    b.ToTable("anomaly_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_anomaly_results_normalized_score", "normalized_anomaly_score BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<System.Net.IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.FinancialTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DestinationAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_account_id");

                    b.Property<decimal?>("DestinationBalanceAfter")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("destination_balance_after");

                    b.Property<decimal?>("DestinationBalanceBefore")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("destination_balance_before");

                    b.Property<Guid>("PerformedById")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_id");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reference_number");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_account_id");

                    b.Property<decimal>("SourceBalanceAfter")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("source_balance_after");

                    b.Property<decimal>("SourceBalanceBefore")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("source_balance_before");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("DestinationAccountId")
                        .HasDatabaseName("ix_transactions_destination_account_id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_reference_number");

                    b.HasIndex("PerformedById", "CreatedAt")
                        .HasDatabaseName("ix_transactions_performed_by_id_created_at");

                    b.HasIndex("SourceAccountId", "CreatedAt")
                        .HasDatabaseName("ix_transactions_source_account_id_created_at");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_transactions_destination_fields", "(type = 'TRANSFER' AND destination_account_id IS NOT NULL AND destination_balance_before IS NOT NULL AND destination_balance_after IS NOT NULL) OR (type <> 'TRANSFER' AND destination_account_id IS NULL AND destination_balance_before IS NULL AND destination_balance_after IS NULL)");

                            t.HasCheckConstraint("ck_transactions_distinct_accounts", "destination_account_id IS NULL OR source_account_id <> destination_account_id");

                            t.HasCheckConstraint("ck_transactions_status", "status IN ('COMPLETED', 'REJECTED')");

                            t.HasCheckConstraint("ck_transactions_type", "type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER')");
                        });
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedById")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_id");

                    b.Property<string>("InvitedRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("invited_role");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupabaseUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("supabase_user_id");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("InvitedById")
                        .HasDatabaseName("ix_invitations_invited_by_id");

                    b.HasIndex("SupabaseUserId")
                        .HasDatabaseName("ix_invitations_supabase_user_id");

                    b.HasIndex("Email", "Status")
                        .HasDatabaseName("ix_invitations_email_status");

                    b.ToTable("invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitations_accept_or_revoke", "accepted_at IS NULL OR revoked_at IS NULL");

                            t.HasCheckConstraint("ck_invitations_role", "invited_role IN ('ADMIN', 'USER')");

                            t.HasCheckConstraint("ck_invitations_status", "status IN ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED')");
                        });
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("AuthUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_auth_user_id");

                    b.ToTable("profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_profiles_role", "role IN ('ADMIN', 'USER')");

                            t.HasCheckConstraint("ck_profiles_status", "status IN ('ACTIVE', 'INACTIVE', 'BLOCKED')");
                        });
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.Account", b =>
                {
                    b.HasOne("IsoGuard.Api.Entities.Profile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_profiles_created_by_id");

                    b.HasOne("IsoGuard.Api.Entities.Profile", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_profiles_owner_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.AnomalyResult", b =>
                {
                    b.HasOne("IsoGuard.Api.Entities.FinancialTransaction", "Transaction")
                        .WithOne("AnomalyResult")
                        .HasForeignKey("IsoGuard.Api.Entities.AnomalyResult", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_anomaly_results_transactions_transaction_id");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.AuditLog", b =>
                {
                    b.HasOne("IsoGuard.Api.Entities.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_profiles_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("IsoGuard.Api.Entities.Account", "DestinationAccount")
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_accounts_destination_account_id");

                    b.HasOne("IsoGuard.Api.Entities.Profile", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_profiles_performed_by_id");

                    b.HasOne("IsoGuard.Api.Entities.Account", "SourceAccount")
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_accounts_source_account_id");

                    b.Navigation("DestinationAccount");

                    b.Navigation("PerformedBy");

                    b.Navigation("SourceAccount");
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.Invitation", b =>
                {
                    b.HasOne("IsoGuard.Api.Entities.Profile", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_profiles_invited_by_id");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.FinancialTransaction", b =>
                {
                    b.Navigation("AnomalyResult");
                });

            modelBuilder.Entity("IsoGuard.Api.Entities.Profile", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
