/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AccountRequestRouteImport } from './routes/account-request'
import { Route as CompleteAccountRouteImport } from './routes/complete-account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as AccountsIdRouteImport } from './routes/accounts/$id'
import { Route as AdminAccountRequestsRouteImport } from './routes/admin/account-requests'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminInvitationsRouteImport } from './routes/admin/invitations'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminSuspiciousTransactionsRouteImport } from './routes/admin/suspicious-transactions'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as TransactionsIdRouteImport } from './routes/transactions/$id'
import { Route as TransactionsNewRouteImport } from './routes/transactions/new'
import { Route as AdminAccountsIndexRouteImport } from './routes/admin/accounts/index'
import { Route as AdminAccountsIdRouteImport } from './routes/admin/accounts/$id'
import { Route as AdminTransactionsIndexRouteImport } from './routes/admin/transactions/index'
import { Route as AdminTransactionsIdRouteImport } from './routes/admin/transactions/$id'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRequestRoute = AccountRequestRouteImport.update({
  id: '/account-request',
  path: '/account-request',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteAccountRoute = CompleteAccountRouteImport.update({
  id: '/complete-account',
  path: '/complete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountRequestsRoute = AdminAccountRequestsRouteImport.update({
  id: '/admin/account-requests',
  path: '/admin/account-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitationsRoute = AdminInvitationsRouteImport.update({
  id: '/admin/invitations',
  path: '/admin/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuspiciousTransactionsRoute =
  AdminSuspiciousTransactionsRouteImport.update({
    id: '/admin/suspicious-transactions',
    path: '/admin/suspicious-transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsIndexRoute = AdminAccountsIndexRouteImport.update({
  id: '/admin/accounts/',
  path: '/admin/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsIdRoute = AdminAccountsIdRouteImport.update({
  id: '/admin/accounts/$id',
  path: '/admin/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsIndexRoute = AdminTransactionsIndexRouteImport.update({
  id: '/admin/transactions/',
  path: '/admin/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsIdRoute = AdminTransactionsIdRouteImport.update({
  id: '/admin/transactions/$id',
  path: '/admin/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/access-denied': typeof AccessDeniedRoute
  '/account-request': typeof AccountRequestRoute
  '/complete-account': typeof CompleteAccountRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-2fa': typeof Verify2faRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/admin/account-requests': typeof AdminAccountRequestsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/suspicious-transactions': typeof AdminSuspiciousTransactionsRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/accounts/': typeof AdminAccountsIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/access-denied': typeof AccessDeniedRoute
  '/account-request': typeof AccountRequestRoute
  '/complete-account': typeof CompleteAccountRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-2fa': typeof Verify2faRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/admin/account-requests': typeof AdminAccountRequestsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/suspicious-transactions': typeof AdminSuspiciousTransactionsRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts': typeof AccountsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
  '/admin/transactions': typeof AdminTransactionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/access-denied': typeof AccessDeniedRoute
  '/account-request': typeof AccountRequestRoute
  '/complete-account': typeof CompleteAccountRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-2fa': typeof Verify2faRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/admin/account-requests': typeof AdminAccountRequestsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/suspicious-transactions': typeof AdminSuspiciousTransactionsRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/accounts/': typeof AdminAccountsIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/access-denied'
    | '/account-request'
    | '/complete-account'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/security'
    | '/sitemap.xml'
    | '/verify-2fa'
    | '/accounts/$id'
    | '/admin/account-requests'
    | '/admin/dashboard'
    | '/admin/invitations'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/suspicious-transactions'
    | '/transactions/$id'
    | '/transactions/new'
    | '/accounts/'
    | '/transactions/'
    | '/admin/accounts/$id'
    | '/admin/transactions/$id'
    | '/admin/users/$id'
    | '/admin/accounts/'
    | '/admin/transactions/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/access-denied'
    | '/account-request'
    | '/complete-account'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/security'
    | '/sitemap.xml'
    | '/verify-2fa'
    | '/accounts/$id'
    | '/admin/account-requests'
    | '/admin/dashboard'
    | '/admin/invitations'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/suspicious-transactions'
    | '/transactions/$id'
    | '/transactions/new'
    | '/accounts'
    | '/transactions'
    | '/admin/accounts/$id'
    | '/admin/transactions/$id'
    | '/admin/users/$id'
    | '/admin/accounts'
    | '/admin/transactions'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/access-denied'
    | '/account-request'
    | '/complete-account'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/security'
    | '/sitemap.xml'
    | '/verify-2fa'
    | '/accounts/$id'
    | '/admin/account-requests'
    | '/admin/dashboard'
    | '/admin/invitations'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/suspicious-transactions'
    | '/transactions/$id'
    | '/transactions/new'
    | '/accounts/'
    | '/transactions/'
    | '/admin/accounts/$id'
    | '/admin/transactions/$id'
    | '/admin/users/$id'
    | '/admin/accounts/'
    | '/admin/transactions/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AccountRequestRoute: typeof AccountRequestRoute
  CompleteAccountRoute: typeof CompleteAccountRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Verify2faRoute: typeof Verify2faRoute
  AccountsIdRoute: typeof AccountsIdRoute
  AdminAccountRequestsRoute: typeof AdminAccountRequestsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInvitationsRoute: typeof AdminInvitationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSuspiciousTransactionsRoute: typeof AdminSuspiciousTransactionsRoute
  TransactionsIdRoute: typeof TransactionsIdRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  AdminAccountsIdRoute: typeof AdminAccountsIdRoute
  AdminTransactionsIdRoute: typeof AdminTransactionsIdRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminAccountsIndexRoute: typeof AdminAccountsIndexRoute
  AdminTransactionsIndexRoute: typeof AdminTransactionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-request': {
      id: '/account-request'
      path: '/account-request'
      fullPath: '/account-request'
      preLoaderRoute: typeof AccountRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-account': {
      id: '/complete-account'
      path: '/complete-account'
      fullPath: '/complete-account'
      preLoaderRoute: typeof CompleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account-requests': {
      id: '/admin/account-requests'
      path: '/admin/account-requests'
      fullPath: '/admin/account-requests'
      preLoaderRoute: typeof AdminAccountRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invitations': {
      id: '/admin/invitations'
      path: '/admin/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AdminInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suspicious-transactions': {
      id: '/admin/suspicious-transactions'
      path: '/admin/suspicious-transactions'
      fullPath: '/admin/suspicious-transactions'
      preLoaderRoute: typeof AdminSuspiciousTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/': {
      id: '/admin/accounts/'
      path: '/admin/accounts'
      fullPath: '/admin/accounts/'
      preLoaderRoute: typeof AdminAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/$id': {
      id: '/admin/accounts/$id'
      path: '/admin/accounts/$id'
      fullPath: '/admin/accounts/$id'
      preLoaderRoute: typeof AdminAccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions/': {
      id: '/admin/transactions/'
      path: '/admin/transactions'
      fullPath: '/admin/transactions/'
      preLoaderRoute: typeof AdminTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions/$id': {
      id: '/admin/transactions/$id'
      path: '/admin/transactions/$id'
      fullPath: '/admin/transactions/$id'
      preLoaderRoute: typeof AdminTransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AccountRequestRoute: AccountRequestRoute,
  CompleteAccountRoute: CompleteAccountRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Verify2faRoute: Verify2faRoute,
  AccountsIdRoute: AccountsIdRoute,
  AdminAccountRequestsRoute: AdminAccountRequestsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInvitationsRoute: AdminInvitationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSuspiciousTransactionsRoute: AdminSuspiciousTransactionsRoute,
  TransactionsIdRoute: TransactionsIdRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  AdminAccountsIdRoute: AdminAccountsIdRoute,
  AdminTransactionsIdRoute: AdminTransactionsIdRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminAccountsIndexRoute: AdminAccountsIndexRoute,
  AdminTransactionsIndexRoute: AdminTransactionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
